services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    image: fastapi_blog_prod:latest
    container_name: fastapi_blog_prod_server
    command: "uv run gunicorn -c app/gunicorn_config.py app.main:app"
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
    networks:
      - blog-backend-tier
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1gb
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 5
          window: 60s

  db:
    image: mongo:7
    container_name: fastapi_blog_prod_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - blog-db:/data/db
    networks:
      - blog-backend-tier
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1gb

volumes:
  blog-db:
    driver: local

networks:
  blog-backend-tier:
    driver: bridge
