# environment
x-volumes: &env-volume
  ALLOWED_HOSTS: "*"
  SECRET_KEY: "uwqr82asfg298ruwh1234uchrbgyu2oriqwnetge5rteriyu2354f3erfewc"

  MONGO_URL: "mongodb://root:password@db:27017/blog_db?authSource=admin"
  TEST_MONGO_URL: "mongodb://root:password@db:27017/test_blog_db?authSource=admin"
  DEBUG: "True"

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: fastapi_blog:latest
    container_name: fastapi_blog_server
    command: "uv run \
      -m debugpy --listen 0.0.0.0:5678 \
      -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      <<: *env-volume
    # env_file: .env
    volumes:
      - ./:/code
      - ./.venv_docker:/code/.venv # overrides the folder
    depends_on:
      - db
    networks:
      - blog-backend-tier

  # db:
  #   image: mongo:5
  #   # restart: always
  #   container_name: fastapi_blog_db_5
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - 27017:27017
  #   expose:
  #     - 27017
  #   volumes:
  #     - blog-db-5:/data/db
  #   networks:
  #     - blog-backend-tier

  # db:
  #   image: mongo:6
  #   # restart: always
  #   container_name: fastapi_blog_db_6
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   ports:
  #     - 27017:27017
  #   expose:
  #     - 27017
  #   volumes:
  #     - blog-db-6:/data/db
  #   networks:
  #     - blog-backend-tier

  db:
    image: mongo:7
    # restart: always
    container_name: fastapi_blog_db_7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - blog-db-7:/data/db
    networks:
      - blog-backend-tier

volumes:
  blog-db-5:
    driver: local
  blog-db-6:
    driver: local
  blog-db-7:
    driver: local

networks:
  blog-backend-tier:
    driver: bridge
