apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
  namespace: blog-app-ns
  labels:
    app: blog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          image: fastapi_blog_prod:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: blog-app-config
            - secretRef:
                name: blog-app-secrets
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
