---
# backend-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: blog-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
  namespace: blog-app-ns
  labels:
    app: blog-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          image: fastapi_blog_prod:latest
          imagePullPolicy: IfNotPresent # pull from local image registry
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: blog-app-config
            - secretRef:
                name: blog-app-secrets
          volumeMounts:
            - name: media-storage
              mountPath: /app/media
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc

---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
  namespace: blog-app-ns
spec:
  type: ClusterIP
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
